 services:
  - type: web
    name: whatsapp-chatbot
    env: python
    plan: starter       # choose plan: starter, standard, etc.
    branch: main        # your repo's default branch
    region: oregon      # pick closest region available to you
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:8080"
    envVars:
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false

